export interface Country {
    code: string;
    name_fr: string;
    name_en: string;
    flag: string;
    capital: string;
    mainColor: string;
    latitude: number;
    longitude: number;
}

export const ALL_COUNTRIES: Country[] = [
    { code: 'AF', name_fr: 'Afghanistan', name_en: 'Afghanistan', flag: '🇦🇫', capital: 'Kabul', mainColor: '#000000', latitude: 33.9391, longitude: 67.7100 },
    { code: 'ZA', name_fr: 'Afrique du Sud', name_en: 'South Africa', flag: '🇿🇦', capital: 'Pretoria', mainColor: '#007749', latitude: -30.5595, longitude: 22.9375 },
    { code: 'AL', name_fr: 'Albanie', name_en: 'Albania', flag: '🇦🇱', capital: 'Tirana', mainColor: '#E41E20', latitude: 41.1533, longitude: 20.1683 },
    { code: 'DZ', name_fr: 'Algérie', name_en: 'Algeria', flag: '🇩🇿', capital: 'Algiers', mainColor: '#006233', latitude: 28.0339, longitude: 1.6596 },
    { code: 'DE', name_fr: 'Allemagne', name_en: 'Germany', flag: '🇩🇪', capital: 'Berlin', mainColor: '#DD0000', latitude: 51.1657, longitude: 10.4515 },
    { code: 'AD', name_fr: 'Andorre', name_en: 'Andorra', flag: '🇦🇩', capital: 'Andorra la Vella', mainColor: '#003087', latitude: 42.5063, longitude: 1.5218 },
    { code: 'AO', name_fr: 'Angola', name_en: 'Angola', flag: '🇦🇴', capital: 'Luanda', mainColor: '#CC092F', latitude: -11.2027, longitude: 17.8739 },
    { code: 'SA', name_fr: 'Arabie saoudite', name_en: 'Saudi Arabia', flag: '🇸🇦', capital: 'Riyadh', mainColor: '#165D31', latitude: 23.8859, longitude: 45.0792 },
    { code: 'AR', name_fr: 'Argentine', name_en: 'Argentina', flag: '🇦🇷', capital: 'Buenos Aires', mainColor: '#74ACDF', latitude: -38.4161, longitude: -63.6167 },
    { code: 'AM', name_fr: 'Arménie', name_en: 'Armenia', flag: '🇦🇲', capital: 'Yerevan', mainColor: '#D90012', latitude: 40.0691, longitude: 45.0382 },
    { code: 'AU', name_fr: 'Australie', name_en: 'Australia', flag: '🇦🇺', capital: 'Canberra', mainColor: '#00008B', latitude: -25.2744, longitude: 133.7751 },
    { code: 'AT', name_fr: 'Autriche', name_en: 'Austria', flag: '🇦🇹', capital: 'Vienna', mainColor: '#ED2939', latitude: 47.5162, longitude: 14.5501 },
    { code: 'AZ', name_fr: 'Azerbaïdjan', name_en: 'Azerbaijan', flag: '🇦🇿', capital: 'Baku', mainColor: '#0092BC', latitude: 40.1431, longitude: 47.5769 },
    { code: 'BS', name_fr: 'Bahamas', name_en: 'Bahamas', flag: '🇧🇸', capital: 'Nassau', mainColor: '#00778B', latitude: 25.0343, longitude: -77.3963 },
    { code: 'BH', name_fr: 'Bahreïn', name_en: 'Bahrain', flag: '🇧🇭', capital: 'Manama', mainColor: '#DA291C', latitude: 26.0667, longitude: 50.5577 },
    { code: 'BD', name_fr: 'Bangladesh', name_en: 'Bangladesh', flag: '🇧🇩', capital: 'Dhaka', mainColor: '#006A4E', latitude: 23.6850, longitude: 90.3563 },
    { code: 'BB', name_fr: 'Barbade', name_en: 'Barbados', flag: '🇧🇧', capital: 'Bridgetown', mainColor: '#00267F', latitude: 13.1939, longitude: -59.5432 },
    { code: 'BE', name_fr: 'Belgique', name_en: 'Belgium', flag: '🇧🇪', capital: 'Brussels', mainColor: '#2D2926', latitude: 50.5039, longitude: 4.4699 },
    { code: 'BZ', name_fr: 'Belize', name_en: 'Belize', flag: '🇧🇿', capital: 'Belmopan', mainColor: '#171691', latitude: 17.1899, longitude: -88.4976 },
    { code: 'BJ', name_fr: 'Bénin', name_en: 'Benin', flag: '🇧🇯', capital: 'Porto-Novo', mainColor: '#008751', latitude: 9.3077, longitude: 2.3158 },
    { code: 'BT', name_fr: 'Bhoutan', name_en: 'Bhutan', flag: '🇧🇹', capital: 'Thimphu', mainColor: '#FF5F00', latitude: 27.5142, longitude: 90.4336 },
    { code: 'BY', name_fr: 'Biélorussie', name_en: 'Belarus', flag: '🇧🇾', capital: 'Minsk', mainColor: '#D22730', latitude: 53.7098, longitude: 27.9534 },
    { code: 'MM', name_fr: 'Birmanie (Myanmar)', name_en: 'Myanmar', flag: '🇲🇲', capital: 'Naypyidaw', mainColor: '#FECB00', latitude: 21.9162, longitude: 95.9560 },
    { code: 'BO', name_fr: 'Bolivie', name_en: 'Bolivia', flag: '🇧🇴', capital: 'Sucre', mainColor: '#D52B1E', latitude: -16.2902, longitude: -63.5887 },
    { code: 'BA', name_fr: 'Bosnie-Herzégovine', name_en: 'Bosnia and Herzegovina', flag: '🇧🇦', capital: 'Sarajevo', mainColor: '#002395', latitude: 43.9159, longitude: 17.6791 },
    { code: 'BW', name_fr: 'Botswana', name_en: 'Botswana', flag: '🇧🇼', capital: 'Gaborone', mainColor: '#75B2DD', latitude: -22.3285, longitude: 24.6849 },
    { code: 'BR', name_fr: 'Brésil', name_en: 'Brazil', flag: '🇧🇷', capital: 'Brasília', mainColor: '#009C3B', latitude: -14.2350, longitude: -51.9253 },
    { code: 'BN', name_fr: 'Brunei', name_en: 'Brunei', flag: '🇧🇳', capital: 'Bandar Seri Begawan', mainColor: '#F7E017', latitude: 4.5353, longitude: 114.7277 },
    { code: 'BG', name_fr: 'Bulgarie', name_en: 'Bulgaria', flag: '🇧🇬', capital: 'Sofia', mainColor: '#00966E', latitude: 42.7339, longitude: 25.4858 },
    { code: 'BF', name_fr: 'Burkina Faso', name_en: 'Burkina Faso', flag: '🇧🇫', capital: 'Ouagadougou', mainColor: '#EF2B2D', latitude: 12.2383, longitude: -1.5616 },
    { code: 'BI', name_fr: 'Burundi', name_en: 'Burundi', flag: '🇧🇮', capital: 'Gitega', mainColor: '#18B637', latitude: -3.3731, longitude: 29.9189 },
    { code: 'KH', name_fr: 'Cambodge', name_en: 'Cambodia', flag: '🇰🇭', capital: 'Phnom Penh', mainColor: '#032EA1', latitude: 12.5657, longitude: 104.9910 },
    { code: 'CM', name_fr: 'Cameroun', name_en: 'Cameroon', flag: '🇨🇲', capital: 'Yaoundé', mainColor: '#007A5E', latitude: 7.3697, longitude: 12.3547 },
    { code: 'CA', name_fr: 'Canada', name_en: 'Canada', flag: '🇨🇦', capital: 'Ottawa', mainColor: '#FF0000', latitude: 56.1304, longitude: -106.3468 },
    { code: 'CV', name_fr: 'Cap-Vert', name_en: 'Cape Verde', flag: '🇨🇻', capital: 'Praia', mainColor: '#003893', latitude: 16.0021, longitude: -24.0131 },
    { code: 'CF', name_fr: 'République centrafricaine', name_en: 'Central African Republic', flag: '🇨🇫', capital: 'Bangui', mainColor: '#003082', latitude: 6.6111, longitude: 20.9394 },
    { code: 'CL', name_fr: 'Chili', name_en: 'Chile', flag: '🇨🇱', capital: 'Santiago', mainColor: '#DA291C', latitude: -35.6751, longitude: -71.5430 },
    { code: 'CN', name_fr: 'Chine', name_en: 'China', flag: '🇨🇳', capital: 'Beijing', mainColor: '#DE2910', latitude: 35.8617, longitude: 104.1954 },
    { code: 'CY', name_fr: 'Chypre', name_en: 'Cyprus', flag: '🇨🇾', capital: 'Nicosia', mainColor: '#D57800', latitude: 35.1264, longitude: 33.4299 },
    { code: 'CO', name_fr: 'Colombie', name_en: 'Colombia', flag: '🇨🇴', capital: 'Bogotá', mainColor: '#FCD116', latitude: 4.5709, longitude: -74.2973 },
    { code: 'KM', name_fr: 'Comores', name_en: 'Comoros', flag: '🇰🇲', capital: 'Moroni', mainColor: '#3D8E33', latitude: -11.8750, longitude: 43.8722 },
    { code: 'CG', name_fr: 'Congo-Brazzaville', name_en: 'Republic of the Congo', flag: '🇨🇬', capital: 'Brazzaville', mainColor: '#009543', latitude: -0.2280, longitude: 15.8277 },
    { code: 'CD', name_fr: 'Congo-Kinshasa', name_en: 'DR Congo', flag: '🇨🇩', capital: 'Kinshasa', mainColor: '#007FFF', latitude: -4.0383, longitude: 21.7587 },
    { code: 'KP', name_fr: 'Corée du Nord', name_en: 'North Korea', flag: '🇰🇵', capital: 'Pyongyang', mainColor: '#ED1C27', latitude: 40.3399, longitude: 127.5101 },
    { code: 'KR', name_fr: 'Corée du Sud', name_en: 'South Korea', flag: '🇰🇷', capital: 'Seoul', mainColor: '#0047A0', latitude: 35.9078, longitude: 127.7669 },
    { code: 'CR', name_fr: 'Costa Rica', name_en: 'Costa Rica', flag: '🇨🇷', capital: 'San José', mainColor: '#CE1126', latitude: 9.7489, longitude: -83.7534 },
    { code: 'CI', name_fr: 'Côte d\'Ivoire', name_en: 'Ivory Coast', flag: '🇨🇮', capital: 'Yamoussoukro', mainColor: '#F77F00', latitude: 7.5400, longitude: -5.5471 },
    { code: 'HR', name_fr: 'Croatie', name_en: 'Croatia', flag: '🇭🇷', capital: 'Zagreb', mainColor: '#FF0000', latitude: 45.1000, longitude: 15.2000 },
    { code: 'CU', name_fr: 'Cuba', name_en: 'Cuba', flag: '🇨🇺', capital: 'Havana', mainColor: '#002A8F', latitude: 21.5218, longitude: -77.7812 },
    { code: 'DK', name_fr: 'Danemark', name_en: 'Denmark', flag: '🇩🇰', capital: 'Copenhagen', mainColor: '#C60C30', latitude: 56.2639, longitude: 9.5018 },
    { code: 'DJ', name_fr: 'Djibouti', name_en: 'Djibouti', flag: '🇩🇯', capital: 'Djibouti', mainColor: '#6AB2E7', latitude: 11.8251, longitude: 42.5903 },
    { code: 'DM', name_fr: 'Dominique', name_en: 'Dominica', flag: '🇩🇲', capital: 'Roseau', mainColor: '#006B3F', latitude: 15.4150, longitude: -61.3710 },
    { code: 'EG', name_fr: 'Égypte', name_en: 'Egypt', flag: '🇪🇬', capital: 'Cairo', mainColor: '#CE1126', latitude: 26.8206, longitude: 30.8025 },
    { code: 'AE', name_fr: 'Émirats arabes unis', name_en: 'United Arab Emirates', flag: '🇦🇪', capital: 'Abu Dhabi', mainColor: '#00732F', latitude: 23.4241, longitude: 53.8478 },
    { code: 'EC', name_fr: 'Équateur', name_en: 'Ecuador', flag: '🇪🇨', capital: 'Quito', mainColor: '#FFCD00', latitude: -1.8312, longitude: -78.1834 },
    { code: 'ER', name_fr: 'Érythrée', name_en: 'Eritrea', flag: '🇪🇷', capital: 'Asmara', mainColor: '#EA0437', latitude: 15.1794, longitude: 39.7823 },
    { code: 'ES', name_fr: 'Espagne', name_en: 'Spain', flag: '🇪🇸', capital: 'Madrid', mainColor: '#AA151B', latitude: 40.4637, longitude: -3.7492 },
    { code: 'EE', name_fr: 'Estonie', name_en: 'Estonia', flag: '🇪🇪', capital: 'Tallinn', mainColor: '#4891D9', latitude: 58.5953, longitude: 25.0136 },
    { code: 'US', name_fr: 'États-Unis', name_en: 'United States', flag: '🇺🇸', capital: 'Washington, D.C.', mainColor: '#001365', latitude: 37.0902, longitude: -95.7129 },
    { code: 'ET', name_fr: 'Éthiopie', name_en: 'Ethiopia', flag: '🇪🇹', capital: 'Addis Ababa', mainColor: '#009A44', latitude: 9.1450, longitude: 40.4897 },
    { code: 'FJ', name_fr: 'Fidji', name_en: 'Fiji', flag: '🇫🇯', capital: 'Suva', mainColor: '#68BFE5', latitude: -17.7134, longitude: 178.0650 },
    { code: 'FI', name_fr: 'Finlande', name_en: 'Finland', flag: '🇫🇮', capital: 'Helsinki', mainColor: '#003580', latitude: 61.9241, longitude: 25.7482 },
    { code: 'FR', name_fr: 'France', name_en: 'France', flag: '🇫🇷', capital: 'Paris', mainColor: '#0055A4', latitude: 46.2276, longitude: 2.2137 },
    { code: 'GA', name_fr: 'Gabon', name_en: 'Gabon', flag: '🇬🇦', capital: 'Libreville', mainColor: '#009E60', latitude: -0.8037, longitude: 11.6094 },
    { code: 'GM', name_fr: 'Gambie', name_en: 'Gambia', flag: '🇬🇲', capital: 'Banjul', mainColor: '#CE1126', latitude: 13.4432, longitude: -15.3101 },
    { code: 'GE', name_fr: 'Géorgie', name_en: 'Georgia', flag: '🇬🇪', capital: 'Tbilisi', mainColor: '#FF0000', latitude: 42.3154, longitude: 43.3569 },
    { code: 'GH', name_fr: 'Ghana', name_en: 'Ghana', flag: '🇬🇭', capital: 'Accra', mainColor: '#CE1126', latitude: 7.9465, longitude: -1.0232 },
    { code: 'GR', name_fr: 'Grèce', name_en: 'Greece', flag: '🇬🇷', capital: 'Athens', mainColor: '#0D5EAF', latitude: 39.0742, longitude: 21.8243 },
    { code: 'GD', name_fr: 'Grenade', name_en: 'Grenada', flag: '🇬🇩', capital: 'St. George\'s', mainColor: '#CE1126', latitude: 12.1165, longitude: -61.6790 },
    { code: 'GT', name_fr: 'Guatemala', name_en: 'Guatemala', flag: '🇬🇹', capital: 'Guatemala City', mainColor: '#4997D0', latitude: 15.7835, longitude: -90.2308 },
    { code: 'GN', name_fr: 'Guinée', name_en: 'Guinea', flag: '🇬🇳', capital: 'Conakry', mainColor: '#CE1126', latitude: 9.9456, longitude: -9.6966 },
    { code: 'GW', name_fr: 'Guinée-Bissau', name_en: 'Guinea-Bissau', flag: '🇬🇼', capital: 'Bissau', mainColor: '#CE1126', latitude: 11.8037, longitude: -15.1804 },
    { code: 'GQ', name_fr: 'Guinée équatoriale', name_en: 'Equatorial Guinea', flag: '🇬🇶', capital: 'Malabo', mainColor: '#3E753B', latitude: 1.6508, longitude: 10.2679 },
    { code: 'GY', name_fr: 'Guyana', name_en: 'Guyana', flag: '🇬🇾', capital: 'Georgetown', mainColor: '#009E49', latitude: 4.8604, longitude: -58.9302 },
    { code: 'HT', name_fr: 'Haïti', name_en: 'Haiti', flag: '🇭🇹', capital: 'Port-au-Prince', mainColor: '#00209F', latitude: 18.9712, longitude: -72.2852 },
    { code: 'HN', name_fr: 'Honduras', name_en: 'Honduras', flag: '🇭🇳', capital: 'Tegucigalpa', mainColor: '#0073CF', latitude: 15.2000, longitude: -86.2419 },
    { code: 'HU', name_fr: 'Hongrie', name_en: 'Hungary', flag: '🇭🇺', capital: 'Budapest', mainColor: '#436F4D', latitude: 47.1625, longitude: 19.5033 },
    { code: 'IN', name_fr: 'Inde', name_en: 'India', flag: '🇮🇳', capital: 'New Delhi', mainColor: '#FF9933', latitude: 20.5937, longitude: 78.9629 },
    { code: 'ID', name_fr: 'Indonésie', name_en: 'Indonesia', flag: '🇮🇩', capital: 'Jakarta', mainColor: '#FF0000', latitude: -0.7893, longitude: 113.9213 },
    { code: 'IQ', name_fr: 'Irak', name_en: 'Iraq', flag: '🇮🇶', capital: 'Baghdad', mainColor: '#CE1126', latitude: 33.2232, longitude: 43.6793 },
    { code: 'IR', name_fr: 'Iran', name_en: 'Iran', flag: '🇮🇷', capital: 'Tehran', mainColor: '#239F40', latitude: 32.4279, longitude: 53.6880 },
    { code: 'IE', name_fr: 'Irlande', name_en: 'Ireland', flag: '🇮🇪', capital: 'Dublin', mainColor: '#169B62', latitude: 53.1424, longitude: -7.6921 },
    { code: 'IS', name_fr: 'Islande', name_en: 'Iceland', flag: '🇮🇸', capital: 'Reykjavík', mainColor: '#02529C', latitude: 64.9631, longitude: -19.0208 },
    { code: 'IL', name_fr: 'Israël', name_en: 'Israel', flag: '🇮🇱', capital: 'Jerusalem', mainColor: '#005EB8', latitude: 31.0461, longitude: 34.8516 },
    { code: 'IT', name_fr: 'Italie', name_en: 'Italy', flag: '🇮🇹', capital: 'Rome', mainColor: '#009246', latitude: 41.8719, longitude: 12.5674 },
    { code: 'JM', name_fr: 'Jamaïque', name_en: 'Jamaica', flag: '🇯🇲', capital: 'Kingston', mainColor: '#009B3A', latitude: 18.1096, longitude: -77.2975 },
    { code: 'JP', name_fr: 'Japon', name_en: 'Japan', flag: '🇯🇵', capital: 'Tokyo', mainColor: '#BC002D', latitude: 36.2048, longitude: 138.2529 },
    { code: 'JO', name_fr: 'Jordanie', name_en: 'Jordan', flag: '🇯🇴', capital: 'Amman', mainColor: '#000000', latitude: 30.5852, longitude: 36.2384 },
    { code: 'KZ', name_fr: 'Kazakhstan', name_en: 'Kazakhstan', flag: '🇰🇿', capital: 'Astana', mainColor: '#00AFCA', latitude: 48.0196, longitude: 66.9237 },
    { code: 'KE', name_fr: 'Kenya', name_en: 'Kenya', flag: '🇰🇪', capital: 'Nairobi', mainColor: '#000000', latitude: -0.0236, longitude: 37.9062 },
    { code: 'KG', name_fr: 'Kirghizistan', name_en: 'Kyrgyzstan', flag: '🇰🇬', capital: 'Bishkek', mainColor: '#E4002B', latitude: 41.2044, longitude: 74.7661 },
    { code: 'KI', name_fr: 'Kiribati', name_en: 'Kiribati', flag: '🇰🇮', capital: 'Tarawa', mainColor: '#EF3340', latitude: -3.3704, longitude: -168.7340 },
    { code: 'XK', name_fr: 'Kosovo', name_en: 'Kosovo', flag: '🇽🇰', capital: 'Pristina', mainColor: '#244AA5', latitude: 42.6026, longitude: 20.9030 },
    { code: 'KW', name_fr: 'Koweït', name_en: 'Kuwait', flag: '🇰🇼', capital: 'Kuwait City', mainColor: '#007A3D', latitude: 29.3117, longitude: 47.4818 },
    { code: 'LA', name_fr: 'Laos', name_en: 'Laos', flag: '🇱🇦', capital: 'Vientiane', mainColor: '#CE1126', latitude: 19.8563, longitude: 102.4955 },
    { code: 'LS', name_fr: 'Lesotho', name_en: 'Lesotho', flag: '🇱🇸', capital: 'Maseru', mainColor: '#00209F', latitude: -29.6099, longitude: 28.2336 },
    { code: 'LV', name_fr: 'Lettonie', name_en: 'Latvia', flag: '🇱🇻', capital: 'Riga', mainColor: '#9E3039', latitude: 56.8796, longitude: 24.6032 },
    { code: 'LB', name_fr: 'Liban', name_en: 'Lebanon', flag: '🇱🇧', capital: 'Beirut', mainColor: '#ED1C24', latitude: 33.8547, longitude: 35.8623 },
    { code: 'LR', name_fr: 'Liberia', name_en: 'Liberia', flag: '🇱🇷', capital: 'Monrovia', mainColor: '#BF0A30', latitude: 6.4281, longitude: -9.4295 },
    { code: 'LY', name_fr: 'Libye', name_en: 'Libya', flag: '🇱🇾', capital: 'Tripoli', mainColor: '#E70013', latitude: 26.3351, longitude: 17.2283 },
    { code: 'LI', name_fr: 'Liechtenstein', name_en: 'Liechtenstein', flag: '🇱🇮', capital: 'Vaduz', mainColor: '#002780', latitude: 47.1660, longitude: 9.5554 },
    { code: 'LT', name_fr: 'Lituanie', name_en: 'Lithuania', flag: '🇱🇹', capital: 'Vilnius', mainColor: '#FDB913', latitude: 55.1694, longitude: 23.8813 },
    { code: 'LU', name_fr: 'Luxembourg', name_en: 'Luxembourg', flag: '🇱🇺', capital: 'Luxembourg', mainColor: '#00A1DE', latitude: 49.8153, longitude: 6.1296 },
    { code: 'MK', name_fr: 'Macédoine du Nord', name_en: 'North Macedonia', flag: '🇲🇰', capital: 'Skopje', mainColor: '#D20000', latitude: 41.6086, longitude: 21.7453 },
    { code: 'MG', name_fr: 'Madagascar', name_en: 'Madagascar', flag: '🇲🇬', capital: 'Antananarivo', mainColor: '#FC3D32', latitude: -18.7669, longitude: 46.8691 },
    { code: 'MY', name_fr: 'Malaisie', name_en: 'Malaysia', flag: '🇲🇾', capital: 'Kuala Lumpur', mainColor: '#010066', latitude: 4.2105, longitude: 101.9758 },
    { code: 'MW', name_fr: 'Malawi', name_en: 'Malawi', flag: '🇲🇼', capital: 'Lilongwe', mainColor: '#000000', latitude: -13.2543, longitude: 34.3015 },
    { code: 'MV', name_fr: 'Maldives', name_en: 'Maldives', flag: '🇲🇻', capital: 'Malé', mainColor: '#D21034', latitude: 3.2028, longitude: 73.2207 },
    { code: 'ML', name_fr: 'Mali', name_en: 'Mali', flag: '🇲🇱', capital: 'Bamako', mainColor: '#14B53A', latitude: 17.5707, longitude: -3.9962 },
    { code: 'MT', name_fr: 'Malte', name_en: 'Malta', flag: '🇲🇹', capital: 'Valletta', mainColor: '#CF142B', latitude: 35.9375, longitude: 14.3754 },
    { code: 'MA', name_fr: 'Maroc', name_en: 'Morocco', flag: '🇲🇦', capital: 'Rabat', mainColor: '#C1272D', latitude: 31.7917, longitude: -7.0926 },
    { code: 'MH', name_fr: 'Îles Marshall', name_en: 'Marshall Islands', flag: '🇲🇭', capital: 'Majuro', mainColor: '#003893', latitude: 7.1315, longitude: 171.1845 },
    { code: 'MU', name_fr: 'Maurice', name_en: 'Mauritius', flag: '🇲🇺', capital: 'Port Louis', mainColor: '#EA2839', latitude: -20.3484, longitude: 57.5522 },
    { code: 'MR', name_fr: 'Mauritanie', name_en: 'Mauritania', flag: '🇲🇷', capital: 'Nouakchott', mainColor: '#00A95C', latitude: 21.0079, longitude: -10.9408 },
    { code: 'MX', name_fr: 'Mexique', name_en: 'Mexico', flag: '🇲🇽', capital: 'Mexico City', mainColor: '#006847', latitude: 23.6345, longitude: -102.5528 },
    { code: 'FM', name_fr: 'Micronésie', name_en: 'Micronesia', flag: '🇫🇲', capital: 'Palikir', mainColor: '#6798CE', latitude: 7.4256, longitude: 150.5508 },
    { code: 'MD', name_fr: 'Moldavie', name_en: 'Moldova', flag: '🇲🇩', capital: 'Chișinău', mainColor: '#0046AE', latitude: 47.4116, longitude: 28.3699 },
    { code: 'MC', name_fr: 'Monaco', name_en: 'Monaco', flag: '🇲🇨', capital: 'Monaco', mainColor: '#CE1126', latitude: 43.7384, longitude: 7.4246 },
    { code: 'MN', name_fr: 'Mongolie', name_en: 'Mongolia', flag: '🇲🇳', capital: 'Ulaanbaatar', mainColor: '#DA2032', latitude: 46.8625, longitude: 103.8467 },
    { code: 'ME', name_fr: 'Monténégro', name_en: 'Montenegro', flag: '🇲🇪', capital: 'Podgorica', mainColor: '#C40308', latitude: 42.7087, longitude: 19.3744 },
    { code: 'MZ', name_fr: 'Mozambique', name_en: 'Mozambique', flag: '🇲🇿', capital: 'Maputo', mainColor: '#00966E', latitude: -18.6657, longitude: 35.5296 },
    { code: 'NA', name_fr: 'Namibie', name_en: 'Namibia', flag: '🇳🇦', capital: 'Windhoek', mainColor: '#003580', latitude: -22.9576, longitude: 18.4904 },
    { code: 'NR', name_fr: 'Nauru', name_en: 'Nauru', flag: '🇳🇷', capital: 'Yaren', mainColor: '#002B7F', latitude: -0.5228, longitude: 166.9315 },
    { code: 'NP', name_fr: 'Népal', name_en: 'Nepal', flag: '🇳🇵', capital: 'Kathmandu', mainColor: '#DC143C', latitude: 28.3949, longitude: 84.1240 },
    { code: 'NI', name_fr: 'Nicaragua', name_en: 'Nicaragua', flag: '🇳🇮', capital: 'Managua', mainColor: '#0067C6', latitude: 12.8654, longitude: -85.2072 },
    { code: 'NE', name_fr: 'Niger', name_en: 'Niger', flag: '🇳🇪', capital: 'Niamey', mainColor: '#E05206', latitude: 17.6078, longitude: 8.0817 },
    { code: 'NG', name_fr: 'Nigeria', name_en: 'Nigeria', flag: '🇳🇬', capital: 'Abuja', mainColor: '#008753', latitude: 9.0820, longitude: 8.6753 },
    { code: 'NO', name_fr: 'Norvège', name_en: 'Norway', flag: '🇳🇴', capital: 'Oslo', mainColor: '#BA0C2F', latitude: 60.4720, longitude: 8.4689 },
    { code: 'NZ', name_fr: 'Nouvelle-Zélande', name_en: 'New Zealand', flag: '🇳🇿', capital: 'Wellington', mainColor: '#00247D', latitude: -40.9006, longitude: 174.8860 },
    { code: 'OM', name_fr: 'Oman', name_en: 'Oman', flag: '🇴🇲', capital: 'Muscat', mainColor: '#DB161B', latitude: 21.5126, longitude: 55.9233 },
    { code: 'UG', name_fr: 'Ouganda', name_en: 'Uganda', flag: '🇺🇬', capital: 'Kampala', mainColor: '#000000', latitude: 1.3733, longitude: 32.2903 },
    { code: 'UZ', name_fr: 'Ouzbékistan', name_en: 'Uzbekistan', flag: '🇺🇿', capital: 'Tashkent', mainColor: '#0099B5', latitude: 41.3775, longitude: 64.5853 },
    { code: 'PK', name_fr: 'Pakistan', name_en: 'Pakistan', flag: '🇵🇰', capital: 'Islamabad', mainColor: '#115740', latitude: 30.3753, longitude: 69.3451 },
    { code: 'PW', name_fr: 'Palaos', name_en: 'Palau', flag: '🇵🇼', capital: 'Ngerulmud', mainColor: '#4AADD6', latitude: 7.5150, longitude: 134.5825 },
    { code: 'PS', name_fr: 'Palestine', name_en: 'Palestine', flag: '🇵🇸', capital: 'Ramallah', mainColor: '#EE2A35', latitude: 31.9522, longitude: 35.2332 },
    { code: 'PA', name_fr: 'Panama', name_en: 'Panama', flag: '🇵🇦', capital: 'Panama City', mainColor: '#DA121A', latitude: 8.5380, longitude: -80.7821 },
    { code: 'PG', name_fr: 'Papouasie-Nouvelle-Guinée', name_en: 'Papua New Guinea', flag: '🇵🇬', capital: 'Port Moresby', mainColor: '#CE1126', latitude: -6.3150, longitude: 143.9555 },
    { code: 'PY', name_fr: 'Paraguay', name_en: 'Paraguay', flag: '🇵🇾', capital: 'Asunción', mainColor: '#D52B1E', latitude: -23.4425, longitude: -58.4438 },
    { code: 'NL', name_fr: 'Pays-Bas', name_en: 'Netherlands', flag: '🇳🇱', capital: 'Amsterdam', mainColor: '#AE1C28', latitude: 52.1326, longitude: 5.2913 },
    { code: 'PE', name_fr: 'Pérou', name_en: 'Peru', flag: '🇵🇪', capital: 'Lima', mainColor: '#D91023', latitude: -9.1900, longitude: -75.0152 },
    { code: 'PH', name_fr: 'Philippines', name_en: 'Philippines', flag: '🇵🇭', capital: 'Manila', mainColor: '#0038A8', latitude: 12.8797, longitude: 121.7740 },
    { code: 'PL', name_fr: 'Pologne', name_en: 'Poland', flag: '🇵🇱', capital: 'Warsaw', mainColor: '#DC143C', latitude: 51.9194, longitude: 19.1451 },
    { code: 'PT', name_fr: 'Portugal', name_en: 'Portugal', flag: '🇵🇹', capital: 'Lisbon', mainColor: '#FF0000', latitude: 39.3999, longitude: -8.2245 },
    { code: 'QA', name_fr: 'Qatar', name_en: 'Qatar', flag: '🇶🇦', capital: 'Doha', mainColor: '#8D1B3D', latitude: 25.3548, longitude: 51.1839 },
    { code: 'DO', name_fr: 'République dominicaine', name_en: 'Dominican Republic', flag: '🇩🇴', capital: 'Santo Domingo', mainColor: '#002D62', latitude: 18.7357, longitude: -70.1627 },
    { code: 'CZ', name_fr: 'République tchèque', name_en: 'Czech Republic', flag: '🇨🇿', capital: 'Prague', mainColor: '#11457E', latitude: 49.8175, longitude: 15.4730 },
    { code: 'RO', name_fr: 'Roumanie', name_en: 'Romania', flag: '🇷🇴', capital: 'Bucharest', mainColor: '#002B7F', latitude: 45.9432, longitude: 24.9668 },
    { code: 'GB', name_fr: 'Royaume-Uni', name_en: 'United Kingdom', flag: '🇬🇧', capital: 'London', mainColor: '#012169', latitude: 55.3781, longitude: -3.4360 },
    { code: 'RU', name_fr: 'Russie', name_en: 'Russia', flag: '🇷🇺', capital: 'Moscow', mainColor: '#DA291C', latitude: 61.5240, longitude: 105.3188 },
    { code: 'RW', name_fr: 'Rwanda', name_en: 'Rwanda', flag: '🇷🇼', capital: 'Kigali', mainColor: '#00A1DE', latitude: -1.9403, longitude: 29.8739 },
    { code: 'KN', name_fr: 'Saint-Christophe-et-Niévès', name_en: 'Saint Kitts and Nevis', flag: '🇰🇳', capital: 'Basseterre', mainColor: '#009E49', latitude: 17.3578, longitude: -62.7830 },
    { code: 'SM', name_fr: 'Saint-Marin', name_en: 'San Marino', flag: '🇸🇲', capital: 'San Marino', mainColor: '#5EB6E4', latitude: 43.9424, longitude: 12.4578 },
    { code: 'VC', name_fr: 'Saint-Vincent-et-les-Grenadines', name_en: 'Saint Vincent and the Grenadines', flag: '🇻🇨', capital: 'Kingstown', mainColor: '#009F4D', latitude: 12.9843, longitude: -61.2872 },
    { code: 'LC', name_fr: 'Sainte-Lucie', name_en: 'Saint Lucia', flag: '🇱🇨', capital: 'Castries', mainColor: '#66CCFF', latitude: 13.9094, longitude: -60.9789 },
    { code: 'SB', name_fr: 'Îles Salomon', name_en: 'Solomon Islands', flag: '🇸🇧', capital: 'Honiara', mainColor: '#0051BA', latitude: -9.6457, longitude: 160.1562 },
    { code: 'SV', name_fr: 'Salvador', name_en: 'El Salvador', flag: '🇸🇻', capital: 'San Salvador', mainColor: '#0F47AF', latitude: 13.7942, longitude: -88.8965 },
    { code: 'WS', name_fr: 'Samoa', name_en: 'Samoa', flag: '🇼🇸', capital: 'Apia', mainColor: '#CE1126', latitude: -13.7590, longitude: -172.1046 },
    { code: 'ST', name_fr: 'Sao Tomé-et-Principe', name_en: 'São Tomé and Príncipe', flag: '🇸🇹', capital: 'São Tomé', mainColor: '#12AD2B', latitude: 0.1864, longitude: 6.6131 },
    { code: 'SN', name_fr: 'Sénégal', name_en: 'Senegal', flag: '🇸🇳', capital: 'Dakar', mainColor: '#00853F', latitude: 14.4974, longitude: -14.4524 },
    { code: 'RS', name_fr: 'Serbie', name_en: 'Serbia', flag: '🇷🇸', capital: 'Belgrade', mainColor: '#C6363C', latitude: 44.0165, longitude: 21.0059 },
    { code: 'SC', name_fr: 'Seychelles', name_en: 'Seychelles', flag: '🇸🇨', capital: 'Victoria', mainColor: '#003D88', latitude: -4.6796, longitude: 55.4920 },
    { code: 'SL', name_fr: 'Sierra Leone', name_en: 'Sierra Leone', flag: '🇸🇱', capital: 'Freetown', mainColor: '#1EB53A', latitude: 8.4606, longitude: -11.7799 },
    { code: 'SG', name_fr: 'Singapour', name_en: 'Singapore', flag: '🇸🇬', capital: 'Singapore', mainColor: '#EF3340', latitude: 1.3521, longitude: 103.8198 },
    { code: 'SK', name_fr: 'Slovaquie', name_en: 'Slovakia', flag: '🇸🇰', capital: 'Bratislava', mainColor: '#0B4EA2', latitude: 48.6690, longitude: 19.6990 },
    { code: 'SI', name_fr: 'Slovénie', name_en: 'Slovenia', flag: '🇸🇮', capital: 'Ljubljana', mainColor: '#005CE6', latitude: 46.1512, longitude: 14.9955 },
    { code: 'SO', name_fr: 'Somalie', name_en: 'Somalia', flag: '🇸🇴', capital: 'Mogadishu', mainColor: '#4189DD', latitude: 5.1521, longitude: 46.1996 },
    { code: 'SD', name_fr: 'Soudan', name_en: 'Sudan', flag: '🇸🇩', capital: 'Khartoum', mainColor: '#007229', latitude: 12.8628, longitude: 30.2176 },
    { code: 'SS', name_fr: 'Soudan du Sud', name_en: 'South Sudan', flag: '🇸🇸', capital: 'Juba', mainColor: '#000000', latitude: 6.8770, longitude: 31.3070 },
    { code: 'LK', name_fr: 'Sri Lanka', name_en: 'Sri Lanka', flag: '🇱🇰', capital: 'Colombo', mainColor: '#8D153A', latitude: 7.8731, longitude: 80.7718 },
    { code: 'SE', name_fr: 'Suède', name_en: 'Sweden', flag: '🇸🇪', capital: 'Stockholm', mainColor: '#006AA7', latitude: 60.1282, longitude: 18.6435 },
    { code: 'CH', name_fr: 'Suisse', name_en: 'Switzerland', flag: '🇨🇭', capital: 'Bern', mainColor: '#D52B1E', latitude: 46.8182, longitude: 8.2275 },
    { code: 'SR', name_fr: 'Suriname', name_en: 'Suriname', flag: '🇸🇷', capital: 'Paramaribo', mainColor: '#377E3F', latitude: 3.9193, longitude: -56.0278 },
    { code: 'SZ', name_fr: 'Eswatini (Swaziland)', name_en: 'Eswatini', flag: '🇸🇿', capital: 'Mbabane', mainColor: '#3E5EB9', latitude: -26.5225, longitude: 31.4659 },
    { code: 'SY', name_fr: 'Syrie', name_en: 'Syria', flag: '🇸🇾', capital: 'Damascus', mainColor: '#CE1126', latitude: 34.8021, longitude: 38.9968 },
    { code: 'TJ', name_fr: 'Tadjikistan', name_en: 'Tajikistan', flag: '🇹🇯', capital: 'Dushanbe', mainColor: '#CC0000', latitude: 38.8610, longitude: 71.2761 },
    { code: 'TW', name_fr: 'Taïwan', name_en: 'Taiwan', flag: '🇹🇼', capital: 'Taipei', mainColor: '#FE0000', latitude: 23.6978, longitude: 120.9605 },
    { code: 'TZ', name_fr: 'Tanzanie', name_en: 'Tanzania', flag: '🇹🇿', capital: 'Dodoma', mainColor: '#1EB53A', latitude: -6.3690, longitude: 34.8888 },
    { code: 'TD', name_fr: 'Tchad', name_en: 'Chad', flag: '🇹🇩', capital: 'N\'Djamena', mainColor: '#002664', latitude: 15.4542, longitude: 18.7322 },
    { code: 'TH', name_fr: 'Thaïlande', name_en: 'Thailand', flag: '🇹🇭', capital: 'Bangkok', mainColor: '#2D2A4A', latitude: 15.8700, longitude: 100.9925 },
    { code: 'TL', name_fr: 'Timor oriental', name_en: 'Timor-Leste', flag: '🇹🇱', capital: 'Dili', mainColor: '#DC241F', latitude: -8.8742, longitude: 125.7275 },
    { code: 'TG', name_fr: 'Togo', name_en: 'Togo', flag: '🇹🇬', capital: 'Lomé', mainColor: '#006A4E', latitude: 8.6195, longitude: 0.8248 },
    { code: 'TO', name_fr: 'Tonga', name_en: 'Tonga', flag: '🇹🇴', capital: 'Nuku\'alofa', mainColor: '#C10000', latitude: -21.1790, longitude: -175.1982 },
    { code: 'TT', name_fr: 'Trinité-et-Tobago', name_en: 'Trinidad and Tobago', flag: '🇹🇹', capital: 'Port of Spain', mainColor: '#CE1126', latitude: 10.6918, longitude: -61.2225 },
    { code: 'TN', name_fr: 'Tunisie', name_en: 'Tunisia', flag: '🇹🇳', capital: 'Tunis', mainColor: '#E70013', latitude: 33.8869, longitude: 9.5375 },
    { code: 'TM', name_fr: 'Turkménistan', name_en: 'Turkmenistan', flag: '🇹🇲', capital: 'Ashgabat', mainColor: '#28974E', latitude: 38.9697, longitude: 59.5563 },
    { code: 'TR', name_fr: 'Turquie', name_en: 'Turkey', flag: '🇹🇷', capital: 'Ankara', mainColor: '#E30A17', latitude: 38.9637, longitude: 35.2433 },
    { code: 'TV', name_fr: 'Tuvalu', name_en: 'Tuvalu', flag: '🇹🇻', capital: 'Funafuti', mainColor: '#5B96D7', latitude: -7.1095, longitude: 177.6493 },
    { code: 'UA', name_fr: 'Ukraine', name_en: 'Ukraine', flag: '🇺🇦', capital: 'Kyiv', mainColor: '#0057B8', latitude: 48.3794, longitude: 31.1656 },
    { code: 'UY', name_fr: 'Uruguay', name_en: 'Uruguay', flag: '🇺🇾', capital: 'Montevideo', mainColor: '#0038A8', latitude: -32.5228, longitude: -55.7658 },
    { code: 'VU', name_fr: 'Vanuatu', name_en: 'Vanuatu', flag: '🇻🇺', capital: 'Port Vila', mainColor: '#D21034', latitude: -15.3767, longitude: 166.9592 },
    { code: 'VA', name_fr: 'Vatican', name_en: 'Vatican City', flag: '🇻🇦', capital: 'Vatican City', mainColor: '#FFE000', latitude: 41.9029, longitude: 12.4534 },
    { code: 'VE', name_fr: 'Venezuela', name_en: 'Venezuela', flag: '🇻🇪', capital: 'Caracas', mainColor: '#CF142B', latitude: 6.4238, longitude: -66.5897 },
    { code: 'VN', name_fr: 'Viêt Nam', name_en: 'Vietnam', flag: '🇻🇳', capital: 'Hanoi', mainColor: '#DA251D', latitude: 14.0583, longitude: 108.2772 },
    { code: 'YE', name_fr: 'Yémen', name_en: 'Yemen', flag: '🇾🇪', capital: 'Sana\'a', mainColor: '#CE1126', latitude: 15.5527, longitude: 48.5164 },
    { code: 'ZM', name_fr: 'Zambie', name_en: 'Zambia', flag: '🇿🇲', capital: 'Lusaka', mainColor: '#198A00', latitude: -13.1339, longitude: 27.8493 },
    { code: 'ZW', name_fr: 'Zimbabwe', name_en: 'Zimbabwe', flag: '🇿🇼', capital: 'Harare', mainColor: '#006433', latitude: -19.0154, longitude: 29.1549 }
];

const Flags: Record<string, any> = {
    AF: require('@/app/assets/flags/af.png'),
    ZA: require('@/app/assets/flags/za.png'),
    AL: require('@/app/assets/flags/al.png'),
    DZ: require('@/app/assets/flags/dz.png'),
    DE: require('@/app/assets/flags/de.png'),
    AD: require('@/app/assets/flags/ad.png'),
    AO: require('@/app/assets/flags/ao.png'),
    SA: require('@/app/assets/flags/sa.png'),
    AR: require('@/app/assets/flags/ar.png'),
    AM: require('@/app/assets/flags/am.png'),
    AU: require('@/app/assets/flags/au.png'),
    AT: require('@/app/assets/flags/at.png'),
    AZ: require('@/app/assets/flags/az.png'),
    BS: require('@/app/assets/flags/bs.png'),
    BH: require('@/app/assets/flags/bh.png'),
    BD: require('@/app/assets/flags/bd.png'),
    BB: require('@/app/assets/flags/bb.png'),
    BE: require('@/app/assets/flags/be.png'),
    BZ: require('@/app/assets/flags/bz.png'),
    BJ: require('@/app/assets/flags/bj.png'),
    BT: require('@/app/assets/flags/bt.png'),
    BY: require('@/app/assets/flags/by.png'),
    MM: require('@/app/assets/flags/mm.png'),
    BO: require('@/app/assets/flags/bo.png'),
    BA: require('@/app/assets/flags/ba.png'),
    BW: require('@/app/assets/flags/bw.png'),
    BR: require('@/app/assets/flags/br.png'),
    BN: require('@/app/assets/flags/bn.png'),
    BG: require('@/app/assets/flags/bg.png'),
    BF: require('@/app/assets/flags/bf.png'),
    BI: require('@/app/assets/flags/bi.png'),
    KH: require('@/app/assets/flags/kh.png'),
    CM: require('@/app/assets/flags/cm.png'),
    CA: require('@/app/assets/flags/ca.png'),
    CV: require('@/app/assets/flags/cv.png'),
    CF: require('@/app/assets/flags/cf.png'),
    CL: require('@/app/assets/flags/cl.png'),
    CN: require('@/app/assets/flags/cn.png'),
    CY: require('@/app/assets/flags/cy.png'),
    CO: require('@/app/assets/flags/co.png'),
    KM: require('@/app/assets/flags/km.png'),
    CG: require('@/app/assets/flags/cg.png'),
    CD: require('@/app/assets/flags/cd.png'),
    KP: require('@/app/assets/flags/kp.png'),
    KR: require('@/app/assets/flags/kr.png'),
    CR: require('@/app/assets/flags/cr.png'),
    CI: require('@/app/assets/flags/ci.png'),
    HR: require('@/app/assets/flags/hr.png'),
    CU: require('@/app/assets/flags/cu.png'),
    DK: require('@/app/assets/flags/dk.png'),
    DJ: require('@/app/assets/flags/dj.png'),
    DM: require('@/app/assets/flags/dm.png'),
    EG: require('@/app/assets/flags/eg.png'),
    AE: require('@/app/assets/flags/ae.png'),
    EC: require('@/app/assets/flags/ec.png'),
    ER: require('@/app/assets/flags/er.png'),
    ES: require('@/app/assets/flags/es.png'),
    EE: require('@/app/assets/flags/ee.png'),
    US: require('@/app/assets/flags/us.png'),
    ET: require('@/app/assets/flags/et.png'),
    FJ: require('@/app/assets/flags/fj.png'),
    FI: require('@/app/assets/flags/fi.png'),
    FR: require('@/app/assets/flags/fr.png'),
    GA: require('@/app/assets/flags/ga.png'),
    GM: require('@/app/assets/flags/gm.png'),
    GE: require('@/app/assets/flags/ge.png'),
    GH: require('@/app/assets/flags/gh.png'),
    GR: require('@/app/assets/flags/gr.png'),
    GD: require('@/app/assets/flags/gd.png'),
    GT: require('@/app/assets/flags/gt.png'),
    GN: require('@/app/assets/flags/gn.png'),
    GW: require('@/app/assets/flags/gw.png'),
    GQ: require('@/app/assets/flags/gq.png'),
    GY: require('@/app/assets/flags/gy.png'),
    HT: require('@/app/assets/flags/ht.png'),
    HN: require('@/app/assets/flags/hn.png'),
    HU: require('@/app/assets/flags/hu.png'),
    IN: require('@/app/assets/flags/in.png'),
    ID: require('@/app/assets/flags/id.png'),
    IQ: require('@/app/assets/flags/iq.png'),
    IR: require('@/app/assets/flags/ir.png'),
    IE: require('@/app/assets/flags/ie.png'),
    IS: require('@/app/assets/flags/is.png'),
    IL: require('@/app/assets/flags/il.png'),
    IT: require('@/app/assets/flags/it.png'),
    JM: require('@/app/assets/flags/jm.png'),
    JP: require('@/app/assets/flags/jp.png'),
    JO: require('@/app/assets/flags/jo.png'),
    KZ: require('@/app/assets/flags/kz.png'),
    KE: require('@/app/assets/flags/ke.png'),
    KG: require('@/app/assets/flags/kg.png'),
    KI: require('@/app/assets/flags/ki.png'),
    XK: require('@/app/assets/flags/xk.png'),
    KW: require('@/app/assets/flags/kw.png'),
    LA: require('@/app/assets/flags/la.png'),
    LS: require('@/app/assets/flags/ls.png'),
    LV: require('@/app/assets/flags/lv.png'),
    LB: require('@/app/assets/flags/lb.png'),
    LR: require('@/app/assets/flags/lr.png'),
    LY: require('@/app/assets/flags/ly.png'),
    LI: require('@/app/assets/flags/li.png'),
    LT: require('@/app/assets/flags/lt.png'),
    LU: require('@/app/assets/flags/lu.png'),
    MK: require('@/app/assets/flags/mk.png'),
    MG: require('@/app/assets/flags/mg.png'),
    MY: require('@/app/assets/flags/my.png'),
    MW: require('@/app/assets/flags/mw.png'),
    MV: require('@/app/assets/flags/mv.png'),
    ML: require('@/app/assets/flags/ml.png'),
    MT: require('@/app/assets/flags/mt.png'),
    MA: require('@/app/assets/flags/ma.png'),
    MH: require('@/app/assets/flags/mh.png'),
    MU: require('@/app/assets/flags/mu.png'),
    MR: require('@/app/assets/flags/mr.png'),
    MX: require('@/app/assets/flags/mx.png'),
    FM: require('@/app/assets/flags/fm.png'),
    MD: require('@/app/assets/flags/md.png'),
    MC: require('@/app/assets/flags/mc.png'),
    MN: require('@/app/assets/flags/mn.png'),
    ME: require('@/app/assets/flags/me.png'),
    MZ: require('@/app/assets/flags/mz.png'),
    NA: require('@/app/assets/flags/na.png'),
    NR: require('@/app/assets/flags/nr.png'),
    NP: require('@/app/assets/flags/np.png'),
    NI: require('@/app/assets/flags/ni.png'),
    NE: require('@/app/assets/flags/ne.png'),
    NG: require('@/app/assets/flags/ng.png'),
    NO: require('@/app/assets/flags/no.png'),
    NZ: require('@/app/assets/flags/nz.png'),
    OM: require('@/app/assets/flags/om.png'),
    UG: require('@/app/assets/flags/ug.png'),
    UZ: require('@/app/assets/flags/uz.png'),
    PK: require('@/app/assets/flags/pk.png'),
    PW: require('@/app/assets/flags/pw.png'),
    PS: require('@/app/assets/flags/ps.png'),
    PA: require('@/app/assets/flags/pa.png'),
    PG: require('@/app/assets/flags/pg.png'),
    PY: require('@/app/assets/flags/py.png'),
    NL: require('@/app/assets/flags/nl.png'),
    PE: require('@/app/assets/flags/pe.png'),
    PH: require('@/app/assets/flags/ph.png'),
    PL: require('@/app/assets/flags/pl.png'),
    PT: require('@/app/assets/flags/pt.png'),
    QA: require('@/app/assets/flags/qa.png'),
    DO: require('@/app/assets/flags/do.png'),
    CZ: require('@/app/assets/flags/cz.png'),
    RO: require('@/app/assets/flags/ro.png'),
    GB: require('@/app/assets/flags/gb.png'),
    RU: require('@/app/assets/flags/ru.png'),
    RW: require('@/app/assets/flags/rw.png'),
    KN: require('@/app/assets/flags/kn.png'),
    SM: require('@/app/assets/flags/sm.png'),
    VC: require('@/app/assets/flags/vc.png'),
    LC: require('@/app/assets/flags/lc.png'),
    SB: require('@/app/assets/flags/sb.png'),
    SV: require('@/app/assets/flags/sv.png'),
    WS: require('@/app/assets/flags/ws.png'),
    ST: require('@/app/assets/flags/st.png'),
    SN: require('@/app/assets/flags/sn.png'),
    RS: require('@/app/assets/flags/rs.png'),
    SC: require('@/app/assets/flags/sc.png'),
    SL: require('@/app/assets/flags/sl.png'),
    SG: require('@/app/assets/flags/sg.png'),
    SK: require('@/app/assets/flags/sk.png'),
    SI: require('@/app/assets/flags/si.png'),
    SO: require('@/app/assets/flags/so.png'),
    SD: require('@/app/assets/flags/sd.png'),
    SS: require('@/app/assets/flags/ss.png'),
    LK: require('@/app/assets/flags/lk.png'),
    SE: require('@/app/assets/flags/se.png'),
    CH: require('@/app/assets/flags/ch.png'),
    SR: require('@/app/assets/flags/sr.png'),
    SZ: require('@/app/assets/flags/sz.png'),
    SY: require('@/app/assets/flags/sy.png'),
    TJ: require('@/app/assets/flags/tj.png'),
    TW: require('@/app/assets/flags/tw.png'),
    TZ: require('@/app/assets/flags/tz.png'),
    TD: require('@/app/assets/flags/td.png'),
    TH: require('@/app/assets/flags/th.png'),
    TL: require('@/app/assets/flags/tl.png'),
    TG: require('@/app/assets/flags/tg.png'),
    TO: require('@/app/assets/flags/to.png'),
    TT: require('@/app/assets/flags/tt.png'),
    TN: require('@/app/assets/flags/tn.png'),
    TM: require('@/app/assets/flags/tm.png'),
    TR: require('@/app/assets/flags/tr.png'),
    TV: require('@/app/assets/flags/tv.png'),
    UA: require('@/app/assets/flags/ua.png'),
    UY: require('@/app/assets/flags/uy.png'),
    VU: require('@/app/assets/flags/vu.png'),
    VA: require('@/app/assets/flags/va.png'),
    VE: require('@/app/assets/flags/ve.png'),
    VN: require('@/app/assets/flags/vn.png'),
    YE: require('@/app/assets/flags/ye.png'),
    ZM: require('@/app/assets/flags/zm.png'),
    ZW: require('@/app/assets/flags/zw.png')
};

export const getFlagImage = (code: string) => {
    // Fallback sur une image "inconnue" si le code manque
    return Flags[code] || require('@/app/assets/flags/unknown_flag.png');
};

export const STARTER_COUNTRIES: Country[] = [
    ALL_COUNTRIES.find(c => c.code === 'FR')!,
    ALL_COUNTRIES.find(c => c.code === 'PE')!,
    ALL_COUNTRIES.find(c => c.code === 'JP')!,
    ALL_COUNTRIES.find(c => c.code === 'EG')!,
];